### ISSUE TITLE
I get "Please fix your recipes so that they properly complete|"

### ISSUE THREAD

**Issue by richstandbrook** [developish/vagrant-wordpress#4]
When I run `vagrant up` I keep getting errors and the box never has mysql/php etc.

```
$ vagrant up
[default] VM already created. Booting if it's not already running...
[default] Clearing any previously set forwarded ports...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] -- 3306 => 3306 (adapter 1)
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Mounting shared folders...
[default] -- v-root: /vagrant
[default] -- v-csc-1: /tmp/vagrant-chef-1/chef-solo-1/cookbooks
[default] -- theme: /var/www/wordpress/wp-content/themes/theme
[default] Running provisioner: Vagrant::Provisioners::ChefSolo...
[default] Generating chef JSON and uploading...
[default] Running chef-solo...
stdin: is not a tty
[2013-03-06T17:14:04+01:00] INFO: *** Chef 10.14.2 ***
[2013-03-06T17:14:05+01:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[wordpress]"] from JSON
[2013-03-06T17:14:05+01:00] INFO: Run List is [recipe[apt], recipe[wordpress]]
[2013-03-06T17:14:05+01:00] INFO: Run List expands to [apt, wordpress]
[2013-03-06T17:14:05+01:00] INFO: Starting Chef Run for lucid32.hsd1.ca.comcast.net.
[2013-03-06T17:14:05+01:00] INFO: Running start handlers
[2013-03-06T17:14:05+01:00] INFO: Start handlers complete.
[2013-03-06T17:14:05+01:00] INFO: Missing gem 'mysql'
[2013-03-06T17:14:05+01:00] INFO: Processing execute[apt-get update] action run (apt::default line 20)
[2013-03-06T17:14:15+01:00] INFO: execute[apt-get update] ran successfully
[2013-03-06T17:14:15+01:00] INFO: Could not find previously defined grants.sql resource
[2013-03-06T17:14:15+01:00] INFO: Processing execute[apt-get update] action nothing (apt::default line 20)
[2013-03-06T17:14:15+01:00] INFO: Processing directory[/var/cache/local] action create (apt::default line 27)
[2013-03-06T17:14:15+01:00] INFO: Processing directory[/var/cache/local/preseeding] action create (apt::default line 27)
[2013-03-06T17:14:15+01:00] INFO: Processing package[apache2] action install (apache2::default line 20)
[2013-03-06T17:14:15+01:00] INFO: Processing service[apache2] action enable (apache2::default line 32)
[2013-03-06T17:14:15+01:00] INFO: Processing directory[/etc/apache2/ssl] action create (apache2::default line 118)
[2013-03-06T17:14:15+01:00] INFO: Processing directory[/etc/apache2/conf.d] action create (apache2::default line 125)
[2013-03-06T17:14:15+01:00] INFO: Processing directory[/var/cache/apache2] action create (apache2::default line 132)
[2013-03-06T17:14:15+01:00] INFO: Processing template[apache2.conf] action create (apache2::default line 138)
[2013-03-06T17:14:16+01:00] INFO: Processing template[security] action create (apache2::default line 152)
[2013-03-06T17:14:16+01:00] INFO: Processing template[charset] action create (apache2::default line 162)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/ports.conf] action create (apache2::default line 172)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/sites-available/default] action create (apache2::default line 181)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/status.conf] action create (apache2::mod_status line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod status] action run (apache2::mod_status line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/alias.conf] action create (apache2::mod_alias line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod alias] action run (apache2::mod_alias line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod auth_basic] action run (apache2::mod_auth_basic line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod authn_file] action run (apache2::mod_authn_file line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod authz_default] action run (apache2::mod_authz_default line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod authz_groupfile] action run (apache2::mod_authz_groupfile line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod authz_host] action run (apache2::mod_authz_host line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod authz_user] action run (apache2::mod_authz_user line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/autoindex.conf] action create (apache2::mod_autoindex line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod autoindex] action run (apache2::mod_autoindex line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/dir.conf] action create (apache2::mod_dir line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod dir] action run (apache2::mod_dir line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod env] action run (apache2::mod_env line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/mime.conf] action create (apache2::mod_mime line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod mime] action run (apache2::mod_mime line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/negotiation.conf] action create (apache2::mod_negotiation line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod negotiation] action run (apache2::mod_negotiation line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing template[/etc/apache2/mods-available/setenvif.conf] action create (apache2::mod_setenvif line 21)
[2013-03-06T17:14:16+01:00] INFO: Processing execute[a2enmod setenvif] action run (apache2::mod_setenvif line 28)
[2013-03-06T17:14:16+01:00] INFO: Processing service[apache2] action start (apache2::default line 207)
[2013-03-06T17:14:16+01:00] INFO: Processing package[mysql-devel] action install (mysql::client line 22)
[2013-03-06T17:14:16+01:00] INFO: Processing gem_package[mysql] action install (mysql::client line 48)

================================================================================

Error executing action `install` on resource 'gem_package[mysql]'

================================================================================


Gem::Installer::ExtensionBuildError

-----------------------------------

ERROR: Failed to build gem native extension.

        /opt/vagrant_ruby/bin/ruby extconf.rb
checking for mysql_ssl_set()... yes
checking for rb_str_set_len()... yes
checking for rb_thread_start_timer()... yes
checking for mysql.h... yes
creating Makefile

make
sh: make: not found


Gem files will remain installed in /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mysql-2.9.1 for inspection.
Results logged to /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mysql-2.9.1/ext/mysql_api/gem_make.out

Resource Declaration:

---------------------

# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/recipes/client.rb

 47: 
 48:   gem_package "mysql" do
 49:     action :install
 50:   end
 51: 

Compiled Resource:

------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/recipes/client.rb:48:in `from_file'

gem_package("mysql") do
  retry_delay 2
  cookbook_name :mysql
  package_name "mysql"
  retries 0
  action [:install]
  recipe_name "client"
  provider Chef::Provider::Package::Rubygems
end

[2013-03-06T17:14:23+01:00] ERROR: Running exception handlers
[2013-03-06T17:14:23+01:00] ERROR: Exception handlers complete
[2013-03-06T17:14:24+01:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-03-06T17:14:24+01:00] FATAL: Gem::Installer::ExtensionBuildError: gem_package[mysql] (mysql::client line 48) had an error: Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /opt/vagrant_ruby/bin/ruby extconf.rb
checking for mysql_ssl_set()... yes
checking for rb_str_set_len()... yes
checking for rb_thread_start_timer()... yes
checking for mysql.h... yes
creating Makefile

make
sh: make: not found


Gem files will remain installed in /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mysql-2.9.1 for inspection.
Results logged to /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mysql-2.9.1/ext/mysql_api/gem_make.out

Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by zumwalt** [comment]
I'm also experiencing this issue. Any ideas?

**Comment by larcher** [comment]
Hitting the same thing -- the error "sh: make: not found" caught my eye first.  Poking around the recipes it looks as if the "build-essential" package should have been installed, which depends on "make."  But neither of those had been installed yet ("vagrant ssh -c 'dpkg -s build-essential'" ).

I'm new to chef, so I'm not sure yet what's missing ...

**Comment by solipsist** [comment]
Adding build-essential to the runlist in the Vagrantfile will fix it:

>   # Enable provisioning with chef solo, specifying a cookbooks path (relative
>   # to this Vagrantfile), and adding some recipes and/or roles.
>   config.vm.provision :chef_solo do |chef|
>     chef.cookbooks_path = "cookbooks"
> **\+    chef.add_recipe "build-essential"**
>     chef.add_recipe "apt"
>     chef.add_recipe "wordpress"

**Comment by rajeev-rahi** [comment]
guys I do have a similar problem....but cant figure out my solution..anyone any idea? here is my log file...please suggest..thanks.

←[0m

================================================================================←[0m

←[31mError executing action `install` on resource 'package[sqldeveloper]'←[0m

================================================================================←[0m

←[0m

Chef::Exceptions::Exec←[0m

----------------------←[0m

dpkg -i /opt/sqldeveloper_3.2.2.deb returned 1, expected 0←[0m

←[0m

Resource Declaration:←[0m

---------------------←[0m

# In /tmp/vagrant-chef-1/chef-solo-2/cookbooks/sqldeveloper/recipes/default.rb

 20: package "sqldeveloper" do
 21:    source "/opt/sqldeveloper_#{node['sqldeveloper']['version']}.deb"
 22:    version node['sqldeveloper']['version']
 23:    provider Chef::Provider::Package::Dpkg
 24:    action :install
 25: end
 26:
←[0m

←[0m
Compiled Resource:←[0m
------------------←[0m

# Declared in /tmp/vagrant-chef-1/chef-solo-2/cookbooks/sqldeveloper/recipes/default.rb:20:in `from_file'

package("sqldeveloper") do
  provider Chef::Provider::Package::Dpkg
  action [:install]
  retries 0
  retry_delay 2
  package_name "sqldeveloper"
  source "/opt/sqldeveloper_3.2.2.deb"
  version "3.2.20.09.87-2"
  cookbook_name :sqldeveloper
  recipe_name "default"
end
←[0m

←[0m
[2013-09-06T01:17:51-05:00] INFO: Running queued delayed notifications before re-raising exception
[2013-09-06T01:17:51-05:00] INFO: template[/usr/local/EAP-6.1.0/jboss-eap-6.1/standalone/configuration/override.properties] sending restart
 action to service[jboss](delayed)
[2013-09-06T01:17:51-05:00] INFO: Processing service[jboss] action restart (jboss::default line 126)
[2013-09-06T01:18:05-05:00] INFO: service[jboss] restarted
[2013-09-06T01:18:05-05:00] ERROR: Running exception handlers
[2013-09-06T01:18:05-05:00] ERROR: Exception handlers complete
[2013-09-06T01:18:05-05:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-09-06T01:18:05-05:00] FATAL: Chef::Exceptions::Exec: package[sqldeveloper](sqldeveloper::default line 20) had an error: Chef::Except
ions::Exec: dpkg -i /opt/sqldeveloper_3.2.2.deb returned 1, expected 0
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by shizus** [comment]
Hi Guys! I'm having troubles with this too. Any ideas?

I've been googling a lot but I still cannot find any answer.
Thanks in advance!

Running chef-solo...
stdin: is not a tty
[2013-10-06T14:33:53+00:00] INFO: **\* Chef 10.14.2 ***
[2013-10-06T14:33:54+00:00] INFO: Setting the run_list to ["recipe[build-essential]", "recipe[rails_env]"] from JSON
[2013-10-06T14:33:54+00:00] INFO: Run List is [recipe[build-essential], recipe[rails_env]]
[2013-10-06T14:33:54+00:00] INFO: Run List expands to [build-essential, rails_env]
[2013-10-06T14:33:54+00:00] INFO: Starting Chef Run for precise64
[2013-10-06T14:33:54+00:00] INFO: Running start handlers
[2013-10-06T14:33:54+00:00] INFO: Start handlers complete.

# 

# Recipe Compile Error in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/ulimit/resources/rule.rb

## NameError

uninitialized constant Chef::Resource::UlimitDomain

## Cookbook Trace:

  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/ulimit/resources/rule.rb:7:in `class_from_file'

## Relevant File Content:

/tmp/vagrant-chef-1/chef-solo-1/cookbooks/ulimit/resources/rule.rb:

  1:  actions :create, :delete
  2:  default_action :create
  3:  
  4:  attribute :type, :kind_of => [Symbol,String], :required => true
  5:  attribute :item, :kind_of => [Symbol,String], :required => true
  6:  attribute :value, :kind_of => [String,Numeric], :required => true
  7:  attribute :domain, :kind_of => [Chef::Resource::UlimitDomain, String], :required => true
  8:  

[2013-10-06T14:33:55+00:00] ERROR: Running exception handlers
[2013-10-06T14:33:55+00:00] ERROR: Exception handlers complete
[2013-10-06T14:33:55+00:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-10-06T14:33:55+00:00] FATAL: NameError: uninitialized constant Chef::Resource::UlimitDomain
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

In addition here is the stacktrace:

Generated at Sun Oct 06 14:39:27 +0000 2013
Chef::Exceptions::CookbookNotFound: Cookbook ruby_build not found. If you're loading ruby_build from another cookbook, make sure you configure the dependency in your metadata
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/cookbook/cookbook_collection.rb:38:in `initialize'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in`call'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `default'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in`default'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:45:in `[]'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:45:in`load_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:33:in `include_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:27:in`each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `include_recipe'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rails_env/recipes/rbenv.rb:19:in`from_file'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/cookbook_version.rb:558:in `load_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:46:in`load_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:33:in `include_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:27:in`each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `include_recipe'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rails_env/recipes/default.rb:21:in`from_file'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/cookbook_version.rb:558:in `load_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:46:in`load_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:33:in `include_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:27:in`each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `include_recipe'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/run_context.rb:79:in`load'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/run_context.rb:75:in `each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/run_context.rb:75:in`load'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/client.rb:198:in `setup_run_context'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/client.rb:418:in`do_run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/client.rb:176:in `run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application/solo.rb:230:in`run_application'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application/solo.rb:218:in `loop'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application/solo.rb:218:in`run_application'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application.rb:70:in `run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/chef-solo:25
/opt/vagrant_ruby/bin/chef-solo:19:in`load'
/opt/vagrant_ruby/bin/chef-solo:19

**Comment by mcropper** [comment]
had the same errors however it worked for me after running `gem install chef` then `vagrant reload`
